### ISSUE TITLE
Datenmanagement Plan

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#10]
Bei 3.1. Datenerhebung
würde ich diese Seite verlinken
https://github.com/Fuenfgeld/TeamDataScDatenmanagementUndArchivierung/wiki/CSV-Dateien-f%C3%BCr-die-Erstellung-der-Datenbank,-Views-und-Schema-der-Datenbank

Eure Dokumentationen sollten als Links im Datenmanagement Plan auftauchen.

Ihr müßt euch bei dem Datenmanagement plan nicht an das Template halten. Teile die kein Sin machen könnt ihr rausnehmen

In 3.2 Könnt ihr eure ETL Strecke dokumentieren. Das fehlt im Moment noch

Diese könnt ihr als extra Seite im Wiki anlegen.
Hier könnt ihr Mapping Tabellen verwendet.
z.B.

## Tabellen name (Stern Schemas)
| Spalten Name| Typ | Beschreibung| QuellDatenbank | Quelltabelle| QuellSpalte|
|-------------- |-----|--------------|-----------------|-------------|------------|
| Diagnose Code| String| Snomed Diagnose Code|  SourceDB| Procedures| Code|

Hier könnt ihr dann auch die ETL Colab books verlinken. 

Eure Auswertung sollte hier auch dokumentiert werden aber dazu werden wir mehr nächste Woche lernen.

**Comment by Fuenfgeld** [comment]
Ihr solltet auch die SQLite Datenbankfiles referenzieren im DMplan

**Comment by Fuenfgeld** [comment]
Generell finde ich euren DMPlan strukturiert er muss jetzt nur noch ausgebaut werden

**Comment by AMB-Git-Hub** [comment]
Ergänzt
