### ISSUE TITLE
Datenschutz-Folgenabschätzung in Wiki

### ISSUE THREAD

**Issue by ahodelin** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#23]
Schreiben des Dokuments
[Datenschutz-Folgenabschätzung](https://github.com/Fuenfgeld/TeamDataScDatenmanagementUndArchivierung/wiki/Datenschutz-Folgenabsch%C3%A4tzung)

Format ist schon vorgegeben

**Comment by AMB-Git-Hub** [comment]
Zur Einsicht der Änderungen hier eine Kopie angelegt: 
https://docs.google.com/document/d/1OW2L44nZpmtkNe_yuWZnLQMKqZR-3EBBHirA2y_gIY4/edit?usp=sharing

Korrekturen und Ergänzungen im Wiki eingefügt. 

@ohoelske @ahodelin  Gerne einmal Gegensicht. Mache neues Issue Korrektur auf, Dokument steht.

**Comment by ahodelin** [comment]
Info von https://docs.google.com/document/d/1OW2L44nZpmtkNe_yuWZnLQMKqZR-3EBBHirA2y_gIY4/edit?usp=sharing in Wiki einfügen.

**Comment by AMB-Git-Hub** [comment]
Habe es bereits übernommen und überarbeitet.
