### ISSUE TITLE
Projektoutline Prädiktionsanalyse COVID 19 in Wiki (Bitte Lesen und Korrigieren)

### ISSUE THREAD

**Issue by ahodelin** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#24]
Um konsistente zu bleiben...
Das Dokument (https://github.com/Fuenfgeld/TeamDataScDatenmanagementUndArchivierung/wiki/Projektoutline-Pr%C3%A4diktionsanalyse-COVID-19) wurde in Wiki (auch in Markdown Format) eingefügt.

**Comment by AMB-Git-Hub** [comment]
Von meiner Seite ok @ohoelske
