### ISSUE TITLE
Dokumentation der Systemumgebung

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#25]
Hi,
Ihr solltet noch eine Extra Seite zur Dokumentation der System Umgebung anlegen.

Hier geht es um:

1. Aufbewahrungsort der Daten (Google DOCS)
a. Google Server
b. Das backup und die Sicherheit wird von google gewährleistet
2. System Umgebung in denen der Code ausgeführt wird
a. Dokumentation der Dependencies wie in dem Video demonstriert
b. Ausführungsort Docker Container auf Google Servern

Verlinkt das Dokument auch in den Datenmanagmentplan

**Comment by ahodelin** [comment]
Dokumentation begonnen.
