### ISSUE TITLE
Gestaltet eure Wiki homepage

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#26]
Sie kann zum Beispiel als Kurzvorstellung des Projektes und als Inhaltsverzeichnis genutzt werden

**Comment by AMB-Git-Hub** [comment]
Werde eine Beschreibung ergänzen

**Comment by AMB-Git-Hub** [comment]
@ohoelske @ahodelin ergänzt.
