### ISSUE TITLE
Wiki Seite für eure Ergebnisse 

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#27]
Erstellt auch eine Seite wo ihr eure Ergebnisse aus den Analysis dokumentiert. Diese sollte die Abildungen und Graphen enthalten um eure Forschungsfrage zu beantworten. Zusammen mit einer kurzen Erläuterung der Ergebnisse.
Sozusagen ein Paper lite.
Diese sollte auch mit euren analyse Colabbooks verlinkt sein

**Comment by ohoelske** [comment]
Abgeschlossen.
