### ISSUE TITLE
Alle Wiki-Seiten überprüfen und korrigieren

### ISSUE THREAD

**Issue by ahodelin** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#28]
Alle Wiki-Seite GENAU durchlesen, Fehler korrigieren und fehlende Information einfügen.

**Comment by AMB-Git-Hub** [comment]
Ok bin dran 👍

**Comment by AMB-Git-Hub** [comment]
- [x] DMP durchgegangen

**Comment by ohoelske** [comment]
DMP und Home noch ein Paar Fehler korrigiert.

**Comment by ohoelske** [comment]
Bin nochmal alle Pages durchgegangen und habe Fehler korrigiert.
