### ISSUE TITLE
Interner Problauf Abschlusspräsentation

### ISSUE THREAD

**Issue by AMB-Git-Hub** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#30]
- [ ] Feedback Inhalt
- [ ] Kommentare noch zu lösender Inhalte
- [ ] Gemeinsame Präsentation in Meets
- [ ] Feedbackrunde
- [ ] To Dos aufteilen
@ahodelin @AMB-Git-Hub @ohoelske

**Comment by ohoelske** [comment]
Termin ist heute um 14:00
