### ISSUE TITLE
3.2 in DMP Erarbeitet / Archivierungskonzept

### ISSUE THREAD

**Issue by ahodelin** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#37]
Hallo zusammen,

ich habe den Punkt 3.2 in dem DMP erarbeitet, noch dazu das Archivierungskonzept geändert.
Bitte überprüfen.

LG

Abel

**Comment by ohoelske** [comment]
Super danke. Habe einen Link zu unserer Cloud erstellt zur Langzeitarchivierung. Hier können alle Daten lang zeit archiviert werden.

https://charitede-my.sharepoint.com/:f:/r/personal/oliver_hoelsken_charite_de/Documents/PREDICT_COVID19?csf=1&web=1&e=KFS34V

**Comment by AMB-Git-Hub** [comment]
Link ist ein Mikrosoft Login, erfüllt aber hier m.E.n. auch den Zweck. Zudem wir Google Cloud ja auch nach dem Kurs noch erhalten bleiben.
