### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#38]
Legt noch eine Sidebar an mit eurem Inhaltsverzeichnis. Das macht das ganze übersichtlicher
![Screen Shot 2021-02-11 at 17 08 24](https://user-images.githubusercontent.com/32547123/107663696-f44ef000-6c8b-11eb-9c9d-73c6866533a5.png)

**Comment by ahodelin** [comment]
Hallo zusammen,

Sidebar wurde erstellt.

LG

Abel
