### ISSUE TITLE
Charakteristika des ursprünglichen Datensatzes

### ISSUE THREAD

**Issue by ahodelin** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#39]
Folgendes wurde in DMP  an Punkt 3.2 Datenerhebung eingefügt:

Charakteristika des ursprünglichen Datensatzes

|Patienten|Menge|
|-|-|
| Patienten in der Studie | 1185|   
| Getestet auf COVID-19 | 995|      
| Positiver Test auf COVID-19 | 951|

**Comment by ohoelske** [comment]
Hi Abel, wir könnten noch überlegen, die "Einteilung Mild = 928" und "Mild = 928" hinzuzufügen 

ähnlich wie in Data Analysis Wiki Punkt 1:

[https://github.com/Fuenfgeld/TeamDataScDatenmanagementUndArchivierung/blob/main/Abbildung%201_Ein-%20und%20Ausschlusskriterien.v2.png](url)

**Comment by ahodelin** [comment]
schon geschehen.
