### ISSUE TITLE
Daten Exploration

### ISSUE THREAD

**Issue by ahodelin** [Fuenfgeld/TeamDataScDatenmanagementUndArchivierung#7]

**Comment by ahodelin** [comment]
Statistik / Maschine Learning mit der Daten von Allergie und COVID-19

**Comment by ahodelin** [comment]
Analysis der Information der Datenbanken für möglichen Fragestellungen

**Comment by AMB-Git-Hub** [comment]
https://colab.research.google.com/drive/1MLS9T7IUxTb6YmlvakUYDplso7TyN2tW?usp=sharing

Habe zusätzliche Codes mit Abel eingefügt

**Comment by AMB-Git-Hub** [comment]
Btw. hier gibt es nun 2 Versionen, ggf. zusammenführen.

**Comment by ohoelske** [comment]
Ich muss das Colab book  noch ins Git überführen.

**Comment by ohoelske** [comment]
Colab book ins git hoch geladen.
